"""last_name nullable, request and requestService models

Revision ID: 43cef753ebb4
Revises: 6403e3aac850
Create Date: 2024-10-15 20:08:57.675723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43cef753ebb4'
down_revision: Union[str, None] = '6403e3aac850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_service',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_request_service_id'), 'request_service', ['id'], unique=False)
    op.create_table('request',
    sa.Column('status', sa.Enum('NEW', 'RAW_SCHEME', 'ON_MEASURE', 'FINALLY_SCHEME', 'COORDINATION', 'ORDER', 'LOST', 'COMPLETED', 'FAKE', name='requeststatus'), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('number_in_program', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('changes_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('request_service_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_service_id'], ['request_service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_id'), 'request', ['id'], unique=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_request_id'), table_name='request')
    op.drop_table('request')
    op.drop_index(op.f('ix_request_service_id'), table_name='request_service')
    op.drop_table('request_service')
    # ### end Alembic commands ###
