"""cascade delete

Revision ID: 6403e3aac850
Revises: 6778190b2dc3
Create Date: 2024-10-13 19:07:01.420542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6403e3aac850'
down_revision: Union[str, None] = '6778190b2dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_user_id_fkey', 'client', type_='foreignkey')
    op.create_foreign_key(None, 'client', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('rolepermission_role_id_fkey', 'rolepermission', type_='foreignkey')
    op.drop_constraint('rolepermission_permission_id_fkey', 'rolepermission', type_='foreignkey')
    op.create_foreign_key(None, 'rolepermission', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rolepermission', 'permission', ['permission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('userroles_role_id_fkey', 'userroles', type_='foreignkey')
    op.drop_constraint('userroles_user_id_fkey', 'userroles', type_='foreignkey')
    op.create_foreign_key(None, 'userroles', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'userroles', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userroles', type_='foreignkey')
    op.drop_constraint(None, 'userroles', type_='foreignkey')
    op.create_foreign_key('userroles_user_id_fkey', 'userroles', 'user', ['user_id'], ['id'])
    op.create_foreign_key('userroles_role_id_fkey', 'userroles', 'role', ['role_id'], ['id'])
    op.drop_constraint(None, 'rolepermission', type_='foreignkey')
    op.drop_constraint(None, 'rolepermission', type_='foreignkey')
    op.create_foreign_key('rolepermission_permission_id_fkey', 'rolepermission', 'permission', ['permission_id'], ['id'])
    op.create_foreign_key('rolepermission_role_id_fkey', 'rolepermission', 'role', ['role_id'], ['id'])
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.create_foreign_key('client_user_id_fkey', 'client', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
